/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProcurementRouteImport } from './routes/procurement'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProcurementIndexRouteImport } from './routes/procurement.index'
import { Route as ProcurementSettingsRouteImport } from './routes/procurement.settings'
import { Route as ProcurementOrdersRouteImport } from './routes/procurement.orders'
import { Route as ProcurementCatalogRouteImport } from './routes/procurement.catalog'
import { Route as ProcurementAnalyticsRouteImport } from './routes/procurement.analytics'
import { Route as ProcurementAgentRouteImport } from './routes/procurement.agent'
import { Route as ApiScanRouteImport } from './routes/api/scan'
import { Route as ApiHybridSearchRouteImport } from './routes/api/hybrid-search'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as ProcurementOrdersOrderIdRouteImport } from './routes/procurement.orders.$orderId'
import { Route as ProcurementCatalogManageRouteImport } from './routes/procurement.catalog.manage'
import { Route as OrdersOrderIdTrackRouteImport } from './routes/orders.$orderId.track'
import { Route as ApiPublicAgentTimeoutsRouteImport } from './routes/api/public/agent-timeouts'
import { Route as ApiPublicAgentmailWebhookRouteImport } from './routes/api/public/agentmail/webhook'

const ProcurementRoute = ProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementIndexRoute = ProcurementIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProcurementRoute,
} as any)
const ProcurementSettingsRoute = ProcurementSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProcurementRoute,
} as any)
const ProcurementOrdersRoute = ProcurementOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ProcurementRoute,
} as any)
const ProcurementCatalogRoute = ProcurementCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => ProcurementRoute,
} as any)
const ProcurementAnalyticsRoute = ProcurementAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ProcurementRoute,
} as any)
const ProcurementAgentRoute = ProcurementAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => ProcurementRoute,
} as any)
const ApiScanRoute = ApiScanRouteImport.update({
  id: '/api/scan',
  path: '/api/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHybridSearchRoute = ApiHybridSearchRouteImport.update({
  id: '/api/hybrid-search',
  path: '/api/hybrid-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementOrdersOrderIdRoute =
  ProcurementOrdersOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => ProcurementOrdersRoute,
  } as any)
const ProcurementCatalogManageRoute =
  ProcurementCatalogManageRouteImport.update({
    id: '/manage',
    path: '/manage',
    getParentRoute: () => ProcurementCatalogRoute,
  } as any)
const OrdersOrderIdTrackRoute = OrdersOrderIdTrackRouteImport.update({
  id: '/$orderId/track',
  path: '/$orderId/track',
  getParentRoute: () => OrdersRoute,
} as any)
const ApiPublicAgentTimeoutsRoute = ApiPublicAgentTimeoutsRouteImport.update({
  id: '/api/public/agent-timeouts',
  path: '/api/public/agent-timeouts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentmailWebhookRoute =
  ApiPublicAgentmailWebhookRouteImport.update({
    id: '/api/public/agentmail/webhook',
    path: '/api/public/agentmail/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRouteWithChildren
  '/procurement': typeof ProcurementRouteWithChildren
  '/admin/products': typeof AdminProductsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/hybrid-search': typeof ApiHybridSearchRoute
  '/api/scan': typeof ApiScanRoute
  '/procurement/agent': typeof ProcurementAgentRoute
  '/procurement/analytics': typeof ProcurementAnalyticsRoute
  '/procurement/catalog': typeof ProcurementCatalogRouteWithChildren
  '/procurement/orders': typeof ProcurementOrdersRouteWithChildren
  '/procurement/settings': typeof ProcurementSettingsRoute
  '/procurement/': typeof ProcurementIndexRoute
  '/api/public/agent-timeouts': typeof ApiPublicAgentTimeoutsRoute
  '/orders/$orderId/track': typeof OrdersOrderIdTrackRoute
  '/procurement/catalog/manage': typeof ProcurementCatalogManageRoute
  '/procurement/orders/$orderId': typeof ProcurementOrdersOrderIdRoute
  '/api/public/agentmail/webhook': typeof ApiPublicAgentmailWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRouteWithChildren
  '/admin/products': typeof AdminProductsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/hybrid-search': typeof ApiHybridSearchRoute
  '/api/scan': typeof ApiScanRoute
  '/procurement/agent': typeof ProcurementAgentRoute
  '/procurement/analytics': typeof ProcurementAnalyticsRoute
  '/procurement/catalog': typeof ProcurementCatalogRouteWithChildren
  '/procurement/orders': typeof ProcurementOrdersRouteWithChildren
  '/procurement/settings': typeof ProcurementSettingsRoute
  '/procurement': typeof ProcurementIndexRoute
  '/api/public/agent-timeouts': typeof ApiPublicAgentTimeoutsRoute
  '/orders/$orderId/track': typeof OrdersOrderIdTrackRoute
  '/procurement/catalog/manage': typeof ProcurementCatalogManageRoute
  '/procurement/orders/$orderId': typeof ProcurementOrdersOrderIdRoute
  '/api/public/agentmail/webhook': typeof ApiPublicAgentmailWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRouteWithChildren
  '/procurement': typeof ProcurementRouteWithChildren
  '/admin/products': typeof AdminProductsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/hybrid-search': typeof ApiHybridSearchRoute
  '/api/scan': typeof ApiScanRoute
  '/procurement/agent': typeof ProcurementAgentRoute
  '/procurement/analytics': typeof ProcurementAnalyticsRoute
  '/procurement/catalog': typeof ProcurementCatalogRouteWithChildren
  '/procurement/orders': typeof ProcurementOrdersRouteWithChildren
  '/procurement/settings': typeof ProcurementSettingsRoute
  '/procurement/': typeof ProcurementIndexRoute
  '/api/public/agent-timeouts': typeof ApiPublicAgentTimeoutsRoute
  '/orders/$orderId/track': typeof OrdersOrderIdTrackRoute
  '/procurement/catalog/manage': typeof ProcurementCatalogManageRoute
  '/procurement/orders/$orderId': typeof ProcurementOrdersOrderIdRoute
  '/api/public/agentmail/webhook': typeof ApiPublicAgentmailWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/orders'
    | '/procurement'
    | '/admin/products'
    | '/api/chat'
    | '/api/hybrid-search'
    | '/api/scan'
    | '/procurement/agent'
    | '/procurement/analytics'
    | '/procurement/catalog'
    | '/procurement/orders'
    | '/procurement/settings'
    | '/procurement/'
    | '/api/public/agent-timeouts'
    | '/orders/$orderId/track'
    | '/procurement/catalog/manage'
    | '/procurement/orders/$orderId'
    | '/api/public/agentmail/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/orders'
    | '/admin/products'
    | '/api/chat'
    | '/api/hybrid-search'
    | '/api/scan'
    | '/procurement/agent'
    | '/procurement/analytics'
    | '/procurement/catalog'
    | '/procurement/orders'
    | '/procurement/settings'
    | '/procurement'
    | '/api/public/agent-timeouts'
    | '/orders/$orderId/track'
    | '/procurement/catalog/manage'
    | '/procurement/orders/$orderId'
    | '/api/public/agentmail/webhook'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/orders'
    | '/procurement'
    | '/admin/products'
    | '/api/chat'
    | '/api/hybrid-search'
    | '/api/scan'
    | '/procurement/agent'
    | '/procurement/analytics'
    | '/procurement/catalog'
    | '/procurement/orders'
    | '/procurement/settings'
    | '/procurement/'
    | '/api/public/agent-timeouts'
    | '/orders/$orderId/track'
    | '/procurement/catalog/manage'
    | '/procurement/orders/$orderId'
    | '/api/public/agentmail/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  ProcurementRoute: typeof ProcurementRouteWithChildren
  AdminProductsRoute: typeof AdminProductsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiHybridSearchRoute: typeof ApiHybridSearchRoute
  ApiScanRoute: typeof ApiScanRoute
  ApiPublicAgentTimeoutsRoute: typeof ApiPublicAgentTimeoutsRoute
  ApiPublicAgentmailWebhookRoute: typeof ApiPublicAgentmailWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/procurement': {
      id: '/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof ProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/': {
      id: '/procurement/'
      path: '/'
      fullPath: '/procurement/'
      preLoaderRoute: typeof ProcurementIndexRouteImport
      parentRoute: typeof ProcurementRoute
    }
    '/procurement/settings': {
      id: '/procurement/settings'
      path: '/settings'
      fullPath: '/procurement/settings'
      preLoaderRoute: typeof ProcurementSettingsRouteImport
      parentRoute: typeof ProcurementRoute
    }
    '/procurement/orders': {
      id: '/procurement/orders'
      path: '/orders'
      fullPath: '/procurement/orders'
      preLoaderRoute: typeof ProcurementOrdersRouteImport
      parentRoute: typeof ProcurementRoute
    }
    '/procurement/catalog': {
      id: '/procurement/catalog'
      path: '/catalog'
      fullPath: '/procurement/catalog'
      preLoaderRoute: typeof ProcurementCatalogRouteImport
      parentRoute: typeof ProcurementRoute
    }
    '/procurement/analytics': {
      id: '/procurement/analytics'
      path: '/analytics'
      fullPath: '/procurement/analytics'
      preLoaderRoute: typeof ProcurementAnalyticsRouteImport
      parentRoute: typeof ProcurementRoute
    }
    '/procurement/agent': {
      id: '/procurement/agent'
      path: '/agent'
      fullPath: '/procurement/agent'
      preLoaderRoute: typeof ProcurementAgentRouteImport
      parentRoute: typeof ProcurementRoute
    }
    '/api/scan': {
      id: '/api/scan'
      path: '/api/scan'
      fullPath: '/api/scan'
      preLoaderRoute: typeof ApiScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hybrid-search': {
      id: '/api/hybrid-search'
      path: '/api/hybrid-search'
      fullPath: '/api/hybrid-search'
      preLoaderRoute: typeof ApiHybridSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/orders/$orderId': {
      id: '/procurement/orders/$orderId'
      path: '/$orderId'
      fullPath: '/procurement/orders/$orderId'
      preLoaderRoute: typeof ProcurementOrdersOrderIdRouteImport
      parentRoute: typeof ProcurementOrdersRoute
    }
    '/procurement/catalog/manage': {
      id: '/procurement/catalog/manage'
      path: '/manage'
      fullPath: '/procurement/catalog/manage'
      preLoaderRoute: typeof ProcurementCatalogManageRouteImport
      parentRoute: typeof ProcurementCatalogRoute
    }
    '/orders/$orderId/track': {
      id: '/orders/$orderId/track'
      path: '/$orderId/track'
      fullPath: '/orders/$orderId/track'
      preLoaderRoute: typeof OrdersOrderIdTrackRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/api/public/agent-timeouts': {
      id: '/api/public/agent-timeouts'
      path: '/api/public/agent-timeouts'
      fullPath: '/api/public/agent-timeouts'
      preLoaderRoute: typeof ApiPublicAgentTimeoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agentmail/webhook': {
      id: '/api/public/agentmail/webhook'
      path: '/api/public/agentmail/webhook'
      fullPath: '/api/public/agentmail/webhook'
      preLoaderRoute: typeof ApiPublicAgentmailWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OrdersRouteChildren {
  OrdersOrderIdTrackRoute: typeof OrdersOrderIdTrackRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersOrderIdTrackRoute: OrdersOrderIdTrackRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface ProcurementCatalogRouteChildren {
  ProcurementCatalogManageRoute: typeof ProcurementCatalogManageRoute
}

const ProcurementCatalogRouteChildren: ProcurementCatalogRouteChildren = {
  ProcurementCatalogManageRoute: ProcurementCatalogManageRoute,
}

const ProcurementCatalogRouteWithChildren =
  ProcurementCatalogRoute._addFileChildren(ProcurementCatalogRouteChildren)

interface ProcurementOrdersRouteChildren {
  ProcurementOrdersOrderIdRoute: typeof ProcurementOrdersOrderIdRoute
}

const ProcurementOrdersRouteChildren: ProcurementOrdersRouteChildren = {
  ProcurementOrdersOrderIdRoute: ProcurementOrdersOrderIdRoute,
}

const ProcurementOrdersRouteWithChildren =
  ProcurementOrdersRoute._addFileChildren(ProcurementOrdersRouteChildren)

interface ProcurementRouteChildren {
  ProcurementAgentRoute: typeof ProcurementAgentRoute
  ProcurementAnalyticsRoute: typeof ProcurementAnalyticsRoute
  ProcurementCatalogRoute: typeof ProcurementCatalogRouteWithChildren
  ProcurementOrdersRoute: typeof ProcurementOrdersRouteWithChildren
  ProcurementSettingsRoute: typeof ProcurementSettingsRoute
  ProcurementIndexRoute: typeof ProcurementIndexRoute
}

const ProcurementRouteChildren: ProcurementRouteChildren = {
  ProcurementAgentRoute: ProcurementAgentRoute,
  ProcurementAnalyticsRoute: ProcurementAnalyticsRoute,
  ProcurementCatalogRoute: ProcurementCatalogRouteWithChildren,
  ProcurementOrdersRoute: ProcurementOrdersRouteWithChildren,
  ProcurementSettingsRoute: ProcurementSettingsRoute,
  ProcurementIndexRoute: ProcurementIndexRoute,
}

const ProcurementRouteWithChildren = ProcurementRoute._addFileChildren(
  ProcurementRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRouteWithChildren,
  ProcurementRoute: ProcurementRouteWithChildren,
  AdminProductsRoute: AdminProductsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiHybridSearchRoute: ApiHybridSearchRoute,
  ApiScanRoute: ApiScanRoute,
  ApiPublicAgentTimeoutsRoute: ApiPublicAgentTimeoutsRoute,
  ApiPublicAgentmailWebhookRoute: ApiPublicAgentmailWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
