/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProcurementRouteImport } from './routes/procurement'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProcurementIndexRouteImport } from './routes/procurement.index'
import { Route as ProcurementOrdersRouteImport } from './routes/procurement.orders'
import { Route as ProcurementCatalogRouteImport } from './routes/procurement.catalog'
import { Route as ProcurementAnalyticsRouteImport } from './routes/procurement.analytics'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminProductsRouteImport } from './routes/admin.products'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementRoute = ProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementIndexRoute = ProcurementIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProcurementRoute,
} as any)
const ProcurementOrdersRoute = ProcurementOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ProcurementRoute,
} as any)
const ProcurementCatalogRoute = ProcurementCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => ProcurementRoute,
} as any)
const ProcurementAnalyticsRoute = ProcurementAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ProcurementRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/procurement': typeof ProcurementRouteWithChildren
  '/settings': typeof SettingsRoute
  '/admin/products': typeof AdminProductsRoute
  '/api/chat': typeof ApiChatRoute
  '/procurement/analytics': typeof ProcurementAnalyticsRoute
  '/procurement/catalog': typeof ProcurementCatalogRoute
  '/procurement/orders': typeof ProcurementOrdersRoute
  '/procurement/': typeof ProcurementIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/settings': typeof SettingsRoute
  '/admin/products': typeof AdminProductsRoute
  '/api/chat': typeof ApiChatRoute
  '/procurement/analytics': typeof ProcurementAnalyticsRoute
  '/procurement/catalog': typeof ProcurementCatalogRoute
  '/procurement/orders': typeof ProcurementOrdersRoute
  '/procurement': typeof ProcurementIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/procurement': typeof ProcurementRouteWithChildren
  '/settings': typeof SettingsRoute
  '/admin/products': typeof AdminProductsRoute
  '/api/chat': typeof ApiChatRoute
  '/procurement/analytics': typeof ProcurementAnalyticsRoute
  '/procurement/catalog': typeof ProcurementCatalogRoute
  '/procurement/orders': typeof ProcurementOrdersRoute
  '/procurement/': typeof ProcurementIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/orders'
    | '/procurement'
    | '/settings'
    | '/admin/products'
    | '/api/chat'
    | '/procurement/analytics'
    | '/procurement/catalog'
    | '/procurement/orders'
    | '/procurement/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/orders'
    | '/settings'
    | '/admin/products'
    | '/api/chat'
    | '/procurement/analytics'
    | '/procurement/catalog'
    | '/procurement/orders'
    | '/procurement'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/orders'
    | '/procurement'
    | '/settings'
    | '/admin/products'
    | '/api/chat'
    | '/procurement/analytics'
    | '/procurement/catalog'
    | '/procurement/orders'
    | '/procurement/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  ProcurementRoute: typeof ProcurementRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement': {
      id: '/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof ProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/': {
      id: '/procurement/'
      path: '/'
      fullPath: '/procurement/'
      preLoaderRoute: typeof ProcurementIndexRouteImport
      parentRoute: typeof ProcurementRoute
    }
    '/procurement/orders': {
      id: '/procurement/orders'
      path: '/orders'
      fullPath: '/procurement/orders'
      preLoaderRoute: typeof ProcurementOrdersRouteImport
      parentRoute: typeof ProcurementRoute
    }
    '/procurement/catalog': {
      id: '/procurement/catalog'
      path: '/catalog'
      fullPath: '/procurement/catalog'
      preLoaderRoute: typeof ProcurementCatalogRouteImport
      parentRoute: typeof ProcurementRoute
    }
    '/procurement/analytics': {
      id: '/procurement/analytics'
      path: '/analytics'
      fullPath: '/procurement/analytics'
      preLoaderRoute: typeof ProcurementAnalyticsRouteImport
      parentRoute: typeof ProcurementRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProcurementRouteChildren {
  ProcurementAnalyticsRoute: typeof ProcurementAnalyticsRoute
  ProcurementCatalogRoute: typeof ProcurementCatalogRoute
  ProcurementOrdersRoute: typeof ProcurementOrdersRoute
  ProcurementIndexRoute: typeof ProcurementIndexRoute
}

const ProcurementRouteChildren: ProcurementRouteChildren = {
  ProcurementAnalyticsRoute: ProcurementAnalyticsRoute,
  ProcurementCatalogRoute: ProcurementCatalogRoute,
  ProcurementOrdersRoute: ProcurementOrdersRoute,
  ProcurementIndexRoute: ProcurementIndexRoute,
}

const ProcurementRouteWithChildren = ProcurementRoute._addFileChildren(
  ProcurementRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  ProcurementRoute: ProcurementRouteWithChildren,
  SettingsRoute: SettingsRoute,
  AdminProductsRoute: AdminProductsRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
